auctions/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("closed_listings", views.closed_listings, name="closed_listings"),
    path("<int:listing_id>/close-auction", views.close_auction, name="close_auction"),
    path("<int:listing_id>", views.listingDetails, name="detail"),
    
    path("login/", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register/", views.register, name="register"),
    
    path("categories", views.categories, name="categories"),
    path("categories/<int:category_id>", views.listings_by_category, name="listings_by_category"),
    
    path("create", views.createListing, name="create"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("myitems", views.my_items, name="my_items"),
    
    path('add_to_watchlist/<int:listing_id>/', views.add_to_watchlist, name="add_to_watchlist"),
    path('remove_from_watchlist/<int:listing_id>/', views.remove_from_watchlist, name="remove_from_watchlist"),
    
    path("<int:listing_id>/place-bid/", views.place_bid, name="place_bid"),
    path("<int:listing_id>/add-comment", views.add_comment, name="add_comment"),
]

commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django import forms
from django.core.exceptions import ValidationError
from django.utils import timezone


class User(AbstractUser):
    id = models.BigAutoField(primary_key=True)
    first_name = models.CharField(max_length=40)
    last_name = models.CharField(max_length=40)
    
    gender_choices = models.TextChoices("Gender", "Male Female None")
    gender = models.CharField(choices=gender_choices, max_length=10)
    
    
def validate_min_price(value):
    if value < 1:
        raise ValidationError('Price must be greater than 0.')
    pass


class Category(models.Model):
    name = models.CharField(max_length=50)
    
    class Meta:
        ordering = ('name',)
        verbose_name_plural = 'Categories'
    
    def __str__(self):
        return self.name.title()


class Listing(models.Model):    
    object_name = models.CharField(max_length=50)
    description = models.CharField(max_length=600, blank=True, null=True)
    image = models.ImageField(upload_to='listings_images', blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='listings', on_delete=models.CASCADE)
    
    is_closed = models.BooleanField(default=False)
    
    starting_bid = models.FloatField(validators=[validate_min_price])
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='listings')
    
    def __str__(self):
        return self.object_name.title()
    
    
class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE)
    
    class Meta:
        unique_together = ['user', 'listing']
    
    
class Bid(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    amount = models.FloatField()
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, default=None)
    
    def __str__(self):
        return f"Bid by {self.user.username} of {self.amount}"

    
    
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    comment_body = models.CharField(max_length=500, default=None)
    listing = models.ForeignKey(Listing, on_delete=models.CASCADE, default=None)
    created_at = models.DateTimeField(default=timezone.now)
    
    class Meta:
        ordering = ['-created_at']
        
    def __str__(self):
        return f"{self.user.username} - {self.created_at}"

auctions/forms.py
from django import forms

from .models import Listing, Comment

class NewListingForm(forms.ModelForm):
    
    class Meta:
        model = Listing
        fields = ("object_name", "category", "description", "image", "starting_bid")
        
        widgets = {
            'category': forms.Select(attrs={
                'class': 'newlisting-field'
            }),
            
            'object_name': forms.TextInput(attrs={
                'class': 'newlisting-field'
            }),
            
            'description': forms.Textarea(attrs={
                'class': 'newlisting-field',
                'id': 'description-field'
            }),
            
            'starting_bid': forms.TextInput(attrs={
                'class': 'newlisting-field'
            }),
        }
        
        
class NewComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment_body']
        widgets = {
            'comment_body': forms.Textarea(attrs={
                'rows': 3,
                'class': 'comment-body'
            })
        }

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.conf import settings

from .models import User, Listing, Watchlist, Bid, Comment, Category
from .forms import NewListingForm, NewComment


def index(request):
    all_listings = Listing.objects.order_by("-created_at").filter(is_closed=False)
    
    listing_watchlist_dict = {}
    if request.user.is_authenticated:
        for listing in all_listings:
            if Watchlist.objects.filter(user=request.user, listing=listing).exists():
                listing_watchlist_dict[listing.id] = True
            
    return render(request, "auctions/index.html", {
        "all_listings": all_listings,
        "listing_watchlist_dict": listing_watchlist_dict
    })
    
    
    
def closed_listings(request):
    closed_listings = Listing.objects.order_by("-created_at").filter(is_closed=True)
    
    return render(request, "auctions/closed_listings.html", {
        "closed_listings": closed_listings
    })



def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")



def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))



def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
            
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    
    else:
        return render(request, "auctions/register.html")



@login_required
def createListing(request):
    if request.method == "POST":
        form = NewListingForm(request.POST, request.FILES)
        
        if form.is_valid():
            
            if 'image' not in request.FILES:
                default_image_url = settings.DEFAULT_LISTING_IMAGE_URL
                form.instance.image = default_image_url
            
            listing = form.save(commit=False)
            listing.created_by = request.user
            listing.save()
                
            return redirect("detail", listing_id=listing.id)
        
        else:
            if not request.POST['starting_bid'].isdigit() or\
                int(request.POST['starting_bid']) <= 0:
                error_message = "Please enter a valid Starting Bid"

                print(form.errors)
            
    else:
        form = NewListingForm()
        error_message = None
        
    return render(request, 'auctions/create.html', {
        "form": form,
        "title": "New Listing",
        "error_message": error_message
    })
    
    
    
@login_required
def close_auction(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    
    if request.user == listing.created_by:
        listing.is_closed = True
        listing.save()
        
    return redirect("closed_listings")
    
    
    
def listingDetails(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    current_bid = Bid.objects.filter(listing=listing).order_by("-amount").first
    comments = Comment.objects.filter(listing=listing)
    form = NewComment()
    
    if request.user.is_authenticated:
        listing_in_watchlist = Watchlist.objects.filter(user=request.user, listing=listing).exists()
    else:
        listing_in_watchlist = False
    
    return render(request, "auctions/detail.html", {
        "listing": listing,
        "listing_in_watchlist": listing_in_watchlist,
        "current_bid": current_bid,
        "comment_form": form,
        "comments": comments
    })
    
    
    
@login_required
def add_to_watchlist(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    
    if not Watchlist.objects.filter(user=request.user, listing=listing).exists():
        watchlist_item = Watchlist(user=request.user, listing=listing)
        watchlist_item.save()
        
    return redirect("watchlist")



@login_required
def remove_from_watchlist(request, listing_id):
    listing = Listing.objects.get(pk=listing_id)
    
    watchlist_item = Watchlist.objects.filter(user=request.user, listing=listing).first()
    if watchlist_item:
        watchlist_item.delete()
        
    return redirect("watchlist")


@login_required
def watchlist(request):
    if request.user.is_authenticated:
        watchlist_listings = Listing.objects.order_by("-created_at").filter(watchlist__user=request.user)
        
        return render(request, "auctions/watchlist.html", {
            "watchlist_listings": watchlist_listings
        })
        
        
        
@login_required
def place_bid(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
    
    if request.user.is_authenticated:
        listing_in_watchlist = Watchlist.objects.filter(user=request.user, listing=listing).exists()
    else:
        listing_in_watchlist = False
        
    comments = Comment.objects.filter(listing=listing)
    form = NewComment()
    
    if request.method == "POST":
        bid_amount = request.POST.get('bid_amount')
        if bid_amount:
            try:
                bid_amount = float(bid_amount)
                
                if bid_amount >= listing.starting_bid:
                    highest_bid = Bid.objects.filter(listing=listing).order_by('-amount').first()
                    if not highest_bid or bid_amount > highest_bid.amount:
                        bid = Bid(user=request.user, listing=listing, amount=bid_amount)
                        bid.save()
                        message = "Bid placed successfully!"
                    else:
                        message = "Your bid must be higher than the current highest bid."
                else:
                    message = "Your bid must be higher than the starting bid."
            
            except ValueError:
                message = "Please enter a valid bid amount"
        
        else:
            message = "Bid amount cannot be empty."
            
    highest_bid = Bid.objects.filter(listing=listing).order_by('-amount').first()
            
    return render(request, "auctions/detail.html", {
        "message": message,
        "listing": listing,
        "listing_in_watchlist": listing_in_watchlist,
        "current_bid": highest_bid,
        "comments": comments,
        "comment_form": form
    })



@login_required
def my_items(request):
    if request.user.is_authenticated:
        my_listings = Listing.objects.filter(created_by=request.user).exclude(is_closed=True)
        return render(request, "auctions/my_items.html", {
            "listings": my_listings
        })
        
        
        
@login_required
def add_comment(request, listing_id):
    listing = get_object_or_404(Listing, pk=listing_id)
        
    if request.method =="POST":
        form = NewComment(request.POST)
        
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.listing = listing
            comment.save()
            return redirect("detail", listing_id=listing_id)
        
        
        
def categories(request):
    categories = Category.objects.all()
    return render(request, "auctions/categories.html", {
        "categories": categories
    })
    
    
    
def listings_by_category(request, category_id):
    category = Category.objects.get(pk=category_id)
    
    listings = Listing.objects.order_by("-created_at").filter(category=category, is_closed=False)
    
    return render(request, "auctions/listings_by_category.html", {
        "listings": listings,
        "category": category
    })

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block title %}Categories{% endblock %}

{% block body %}

    <p class="subtitle-ph">Categories</p>
    <hr>

    <div class="categories-container">
        {% for category in categories %}
            <a href="{% url 'listings_by_category' category.id %}">
                <div class="category-div">
                    <p style="margin: 0;">{{ category.name }}</p>
                </div>
            </a>
        {% endfor %}
    </div>
{% endblock %}

auctions/templates/auctions/closed_listings.html
{% extends "auctions/layout.html" %}

{% block title %}Closed Auctions{% endblock %}

{% block body %}

    <p class="subtitle-ph">Closed Listings</p>
    <hr>

    {% if closed_listings %}
        {% for listing in closed_listings %}
            <div class="active-listing-container">
                
                <a href="{% url 'detail' listing.id %}"><div class="img-div">
                    <img class="listing-image" src="{{ listing.image.url }}" alt="">
                </div></a>

                <div class="listing-details-index">

                    <div class="inline-block-elem">
                        <a href="{% url 'detail' listing.id %}">
                        <span class="listing-title">{{ listing.object_name.title }}</span></a>
                    </div>

                    <div class="">
                        <span class="key-ph">STATUS</span> - {% if listing.is_closed %}Closed{% else %}Active{% endif %}
                    </div>

                    <div class="">
                        <span class="key-ph">DESCRIPTION</span>
                        <br>
                        {{ listing.description }}
                    </div>

                    <div class="">
                        <span class="key-ph">STARTING BID</span> - {{ listing.starting_bid }} $
                    </div>

                    <div class="">
                        <span class="key-ph">CATEGORY</span> - {{ listing.category }}
                    </div>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <p class="no-closed-ph">There are currently no closed listings.</p>
        <p class="no-closed-ph">See <a class="color-links" href="{% url 'index' %}">Active Listings</a>.</p>
    {% endif %}
{% endblock %}

auctions/templates/auctions/create.html
{% extends 'auctions/layout.html' %}

{% block title %}
    {{ title }}
{% endblock %}

{% block body %}

<p class="subtitle-ph">{{ title }}</p>
<hr>



    <form action="create" method="POST" enctype="multipart/form-data">
        {% csrf_token %}

        <div class="create-form-body">
            <div class="form-field">
                <label class="form-label" for="object_name">Name: </label>
                {{ form.object_name }}
            </div>

            <div class="form-field">
                <label class="form-label" for="category">Category: </label>
                {{ form.category }} 
            </div>


            <div class="form-field">
                <label class="form-label" for="description">Description: </label>
                {{ form.description }}
            </div>

            <div class="form-field">
                <label class="form-label" for="starting_bid">Starting Bid ($): </label>
                {{ form.starting_bid }}
            </div>

            {% if error_message %}
                <div>{{ error_message }}</div>
            {% endif %}

            <div class="form-field">
                <label class="form-label" for="image">Image: </label>
                {{ form.image }}
            </div>

            <button id="submit-btn" type="submit" class="add-remove-watchlist">Submit</button>
        </div>
    </form>

</div>
{% endblock %}

auctions/templates/auctions/detail.html
{% extends "auctions/layout.html" %}

{% block title %} {{ listing.object_name }}{% endblock %}

{% block body %}
    <div class="">

        {% if "success" in message %}
            <div class="alert alert-success" role="alert">
                {{ message }}
            </div>
        {% elif message %}
            <div class="alert alert-danger" role="alert">
                {{ message }}
            </div>
        {% endif %}
        
        <div class="item-details-container">
            <img class="listing-image" src="{{ listing.image.url }}" alt="">

            <div class="item-details-description">
                {% if listing.is_closed %}
                    <div class="won-item-div">
                        <p style="margin: 0;">This auction was won by{% if request.user == current_bid.user %} <strong>YOU</strong>{% else %} <strong>@{{ current_bid.user }}</strong>{% endif %} for <strong>{{ current_bid.amount }} $</strong></p>
                    </div>
                {% endif %}
                <p class="listing-title">{{ listing.object_name.title }}</p>
                <div>
                    <span class="key-ph">STATUS</span> - {% if listing.is_closed %}Closed{% else %}Active{% endif %}
                </div>

                <div>
                    <span class="key-ph">DESCRIPTION</span>
                    <br>
                    {{ listing.description }}
                </div>

                <div>
                    <span class="key-ph">CATEGORY</span> - {{ listing.category }}
                </div>

                <div>
                    <span class="key-ph">STARTING BID</span> - {{ listing.starting_bid }} $
                </div>

                <div>
                    <span class="key-ph">SELLER</span> - @{{ listing.created_by }}
                </div>
            </div>
        

            {% if user.is_authenticated %}
            {% if request.user != listing.created_by and listing.is_closed == False %}
                {% if listing_in_watchlist %}
                    <form action="{% url 'remove_from_watchlist' listing.id %}" method="POST" class="">
                        {% csrf_token %}
                        <button id="details-watchlist-button" class="add-remove-watchlist" type="submit">Remove from Watchlist</button>
                    </form>
                {% else %}
                    <form action="{% url 'add_to_watchlist' listing.id %}" method="POST">
                        {% csrf_token %}
                        <button id="details-watchlist-button" class="add-remove-watchlist" type="submit">Add to Watchlist</button>
                    </form>
                {% endif %}
            {% endif %}
            {% endif %}
        </div>

        {% if listing.is_closed == False %}
        <div class="bid1-div">
            <p style="margin: 0;"><strong>Current bid:</strong>
                {% if current_bid %}{{ current_bid.amount }} ${% else %}There are no bids for this item yet.{% endif %}</p>
                {% if current_bid %}
                    <p style="margin: 0;"><strong>Current winner:</strong> @{{ current_bid.user }}</p>
                {% endif %}
        </div>
        {% endif %}
        
        {% if request.user != listing.created_by  and request.user.is_authenticated and listing.is_closed == False %}

            <form action="{% url 'place_bid' listing.id %}" method="POST">
                {% csrf_token %}
                <div class="place-bid-form">
                    <label style="margin: 0;
                    font-size: 18px;
                    font-weight: 500;" for="bid_amount">Your Bid:</label>
                    <input class="place-bid-input" type="number" name="bid_amount" step="0.5" required>
                    <button class="place-bid-btn" type="submit">Place Bid</button>
                </div>
            </form>

        {% elif request.user == listing.created_by and listing.is_closed == False %}
            <div class="my-items">
                <div class="you-own-div">
                    <p style="margin: 0;">You own this item.</p>
                </div>
                {% if not listing.is_closed and current_bid %}
                <form action="{% url 'close_auction' listing.id %}" method="POST">
                    {% csrf_token %}
                    <button class="close-auction-btn" type="submit">Close Auction</button>
                </form>
                {% endif %}
            </div>
        {% endif %}

        {% if current_bid %}
            <div class="bids-history-div">
                <p class="subtitle-ph">Bid History</p>
                <hr>
                <p class="bid-history-ph"><strong>Number of bids</strong> - {{listing.bid_set.all.count}}</p>
                
                <div class="div-flex">
                    {% for bid in listing.bid_set.all %}
                    <div class="bid-div">
                        <p style="margin: 0;">@{{ bid.user.username }}</p>
                        <p style="margin: 0;
                        font-weight: 500;">{{ bid.amount }} $</p>
                    </div>
                    {% endfor %}
                </div>
                
            </div>
        {% endif %}

        {% if comments %}
            <p class="subtitle-ph" style="margin-left: 20px;
            margin-top: 50px;
            ">Comments</p>
            <hr style="margin-left: 20px;">
            <div class="comms-history-div">
                {% for comment in comments %}
                    <div class="comm13">
                        <div style="display: flex;
                        justify-content: space-between;">
                            <p style="font-weight: 600;">@{{ comment.user }}</p>
                            <p>{{ comment.created_at }}</p>
                        </div>
                        
                        <div class="she-said">{{ comment.comment_body }}</div>
                    </div>
                {% endfor %}
            </div>
        {% endif %}

        {% if user.is_authenticated %}
            <div class="add-comment-div">
                <p style="font-weight: 500;
                font-size: 25px;
                margin: 0;">Add a comment</p>
                <form action="{% url 'add_comment' listing.id %}" method="POST">
                    {% csrf_token %}
                    <div style="display: flex;
                    flex-direction: column;
                    row-gap: 10px;">
                        {{ comment_form.comment_body }}
                        <button class="add-remove-watchlist" id="comm-btn" type="submit">Submit Comment</button>
                    </div>
                </form>
            </div>
        {% endif %}
    </div>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <p class="subtitle-ph">Active Listings</p>

    <hr>

    {% for listing in all_listings %}
    <div class="active-listing-container">

        <a href="{% url 'detail' listing.id %}"><div class="img-div">
            <img class="listing-image" src="{{ listing.image.url }}" alt="">
        </div></a>

        <div class="listing-details-index">
            
            <div class="inline-block-elem">
                <a href="{% url 'detail' listing.id %}">
                    <span class="listing-title">{{ listing.object_name.title }}</span></a>
            </div>

            <div class="">
                <span class="key-ph">STATUS</span> - {% if listing.is_closed %}Closed{% else %}Active{% endif %}
            </div>

            <div class="">
                <span class="key-ph">DESCRIPTION</span>
                <br>
                {{ listing.description }}
            </div>

            <div class="">
                <span class="key-ph">STARTING BID</span> - {{ listing.starting_bid }} $
            </div>

            <div class="">
                <span class="key-ph">CATEGORY</span> - {{ listing.category }}
            </div>


            {% if user.is_authenticated %}
            {% if request.user != listing.created_by %}
                {% if listing.id in listing_watchlist_dict %}
                    <form action="{% url 'remove_from_watchlist' listing.id %}" method="POST" class="">
                        {% csrf_token %}
                        <button class="add-remove-watchlist" type="submit">Remove from Watchlist</button>
                    </form>
                {% else %}
                    <form action="{% url 'add_to_watchlist' listing.id %}" method="POST">
                        {% csrf_token %}
                        <button class="add-remove-watchlist" type="submit">Add to Watchlist</button>
                    </form>
                {% endif %}
            {% else %}
                <p class="you-own-ph">YOU OWN THIS ITEM</p>
            {% endif %}
            {% endif %}
        </div>

    </div>
    {% endfor %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        <link href="{% static 'auctions/reset.css' %}" rel="stylesheet">
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Exo:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
    </head>

    <body>
        <p class="title-ph">Auctions</p>
        <div>
            {% if user.is_authenticated %}
                <p class="username-ph">Signed in as <strong>@{{ user.username }}</strong>.</p>
            {% else %}
                <p class="username-ph">Not signed in.</p>
            {% endif %}
        </div>

        <ul class="nav">

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Active Listings</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'closed_listings' %}">Closed Listings</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'categories' %}">Categories</a>
                </li>


            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'my_items' %}">My Items</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'create' %}">Create Listing</a>
                </li>
                <li class="nav-item exclude-right">
                    <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
                </li>
            {% else %}
                <div class="exclude-right" id="exclude-right-div">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                </div>
            {% endif %}
        </ul>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <p class="subtitle-ph">Login</p>

    <hr>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'register' %}" class="color-links">Register here</a>.

{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <p class="subtitle-ph">Register</p>

    <hr>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input required class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input required class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input required class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input required class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'login' %}" class="color-links">Log In here</a>.

{% endblock %}